### ISSUE TITLE
Change: Better Argument parsing

### ISSUE THREAD

**Issue by iinsertNameHere** [iinsertNameHere/catnip#32]
**Is your feature request related to a problem? Please describe.**
The argument parsing code is getting messy!

**Describe the solution you'd like**
Some how find a better and cleaner way of parsing command line args.

**Comment by yu-kiat** [comment]
I don't think that most of the argument parsing code is messy, it's just the help list which look out of place.

**Comment by iinsertNameHere** [comment]
I would like to replace the argument parsing with some sort of lib or maybe use [parseopt](https://nim-lang.org/docs/parseopt.html).
