### ISSUE TITLE
Change: Better project structure

### ISSUE THREAD

**Issue by iinsertNameHere** [iinsertNameHere/catnip#33]
**Is your feature request related to a problem? Please describe.**
The project structure is not very well thought through! 

**Describe the solution you'd like**
1. Collect ideas on how to structure the project.
2. Implement those ideas.
3. Write docs on how to implement the project structure for future contributors.

**Comment by iinsertNameHere** [comment]
## Please comment if you have a different idea!!!

<br>
<br>
<br>

**I was thinking something like this:**
```text
src
├── catnip.nim (main file)
└── catniplib
    ├── common
    │   ├── declarations.nim (originaly defs.nim)
    │   └── parsetoml.nim (originaly toml.nim)
    |
    ├── terminal
    |   ├── colors.nim
    |   ├── logging.nim
    |   └── argparse.nim (argument parsing lib of some sort) 
    |    
    ├── drawing
    |   └── render.nim
    |
    ├── generation
    │   ├── stats.nim
    |   └── utils.nim
    |
    └── platform
        ├── fetch.nim
        └── probe.nim (originaly platfrom.nim)
      
```

**common:**
Holds everything that is commonly used in most other files and 3rd-party stuff.

**terminal:**
Holds everything that is related to terminal back-end stuff like parsing arguments and handling colors.

**drawing:**
Holds front-end stuff like the render functions.

**generation:**
Holds stuff related to generating data for the front-end.

**platform:**
Holds everything related to retrieving system information. 

**catnip.nim**
Binds all components together.

**Comment by JustBuddy** [comment]
Looks good to me.
I take that you want whole-words (terminal instead of term) for the structure?
That is fine, I think, especially on Linux, it's just usually shortened. (bin, lib etc.)

Instead of “common” I would propose “libraries” or something similar. I only ever saw the term common used in Steams steamapps directory, and there it doesn't make too much sense either, IMHO.

**Comment by iinsertNameHere** [comment]
@JustBuddy 
I think "libraries" wouldn't make so much sense either because for example "definitions.nim" isn't really a lib. The only lib in "common" is "parsetoml.nim". Maybe "common" could become "global" or some thing like that, as the the stuff in this dir is shared in almost every file. Then we could create a new directory called "libraries" and move "parsetoml.nim" in to there.
