### ISSUE TITLE
New Feature: Add Tests

### ISSUE THREAD

**Issue by iinsertNameHere** [iinsertNameHere/catnip#38]
### Describe the solution you'd like
Some sort of Tests would be nice in order to test the whole functionality of catnip before pushing.

### Additional context
I don't know shit about testing... ;)

**Comment by yu-kiat** [comment]
`nim check` could be used to check for any errors.
anyways, if there's an error with the code the program shouldn't be able to be compiled, right?

**Comment by yu-kiat** [comment]
> `nim check` could be used to check for any errors. anyways, if there's an error with the code the program shouldn't be able to be compiled, right?

this can be done by a simple one-line shell scrpt:
```shell
for f in src/*/*/*; do nim check $f; done
```

**Comment by iinsertNameHere** [comment]
But it would also be nice if you could test if every function of catnip works without crashing...
