### ISSUE TITLE
formatting config.toml kills the app

### ISSUE THREAD

**Issue by YoruNoKen** [iinsertNameHere/catnip#49]
### Describe the bug
Using a formatter for the .toml file kills the app

### Screenshots
This works fine
![image](https://github.com/iinsertNameHere/catnip/assets/69751661/d0cc3562-7597-46a6-9bb8-6e0fe5fa57f2)
![image](https://github.com/iinsertNameHere/catnip/assets/69751661/67bcecf4-132d-48bd-a225-7344429d84db)

However this doesn't
![image](https://github.com/iinsertNameHere/catnip/assets/69751661/c33abd23-7150-4847-9d29-a8045f9eb0d4)
![image](https://github.com/iinsertNameHere/catnip/assets/69751661/0feae614-a632-4228-889e-baa6dd16a7aa)

### Device:
 - OS: Linux
 - WM: KDE Plasma 6

**Comment by iinsertNameHere** [comment]
@YoruNoKen  What formatting tool did you use? I'm trying to reproduce your error

**Comment by YoruNoKen** [comment]
can't see what formatter it is, but I assume it's the default on in vscode for .toml files

**Comment by iinsertNameHere** [comment]
@YoruNoKen What extension do you use with toml. I have better toml and no formatter is installed.

**Comment by YoruNoKen** [comment]
@iinsertNameHere I have the `Even Better TOML` extension installed.
the point is: if you look at my second picture, you can see the spaces  between characters gets cut down to 1

**Comment by iinsertNameHere** [comment]
Ah, now I see what the problem is. In [config.toml](https://github.com/iinsertNameHere/catnip/blob/main/config/config.toml) the margin array is "," terminated. After formatting that extra "," is missing. For some reason you have to put a extra "," in arrays when all values in that array are "0". (Planning on replacing that buggy toml parser soon...)

**Comment by YoruNoKen** [comment]
alright, good thing we found out the issue!
