### ISSUE TITLE
[Feature]: Multiple disks

### ISSUE THREAD

**Issue by JustBuddy** [iinsertNameHere/catnip#60]
### Is your feature request related to a problem? Please describe:
I would love to see the disk stat of multiple defined disks, instead of only the internal disk.

Example:
I got the internal disk which is 32 GB, and two external drives which I would like to see the disk stat of.

### Describe the solution you'd like:
In config.toml, add a few commented-out placeholder entries like disk0-disk5, disk0 being the current disk entry.
Further, in that same config file, allow specifications of the disks to show. Either mountpoint or device name, whatever works.

```
[disk.mountpoints]
disk0 =
disk1 =
disk2 =
disk3 =
disk4 =
disk5 =
```

**Comment by iinsertNameHere** [comment]
Nice Idea!

**Comment by yu-kiat** [comment]
> @JustBuddy To do this, I would first have to get a list of all the drives mounting location.

This can be done with `blkid`.

**Comment by iinsertNameHere** [comment]
Yes, but it would be nice to do this using nim or c++ so catnip dose Not need another dependancy.

**Comment by iinsertNameHere** [comment]
@JustBuddy  Should work for now . See README.md for docs

**Comment by JustBuddy** [comment]
@iinsertNameHere I struggle understanding how to define the path or name the disks, I can't make it out based on the readme.

**Comment by iinsertNameHere** [comment]
@JustBuddy you can add Disks by Index.

disk: Disk with Index 0
disk_1: Disk with Index 1

You can View it Like an Array where all your Disks are in..

**Comment by JustBuddy** [comment]
@iinsertNameHere yes but where do I define which index is for which disk?

**Comment by iinsertNameHere** [comment]
@JustBuddy What dose "-g disks" show you?

**Comment by JustBuddy** [comment]
@iinsertNameHere 

When nim setup: `/home/pi/catnip/src/catnip.nim(19, 8) Warning: use dirExists; existsDir is deprecated [Deprecated]`
when running catnip: 
```
tables.nim(234)          raiseKeyError
Error: unhandled exception: key not found: packages [KeyError]
```
when running catnip -g disks
```
tables.nim(234)          raiseKeyError
Error: unhandled exception: key not found: disks [KeyError]
```

Catnip doesn't build rn on my system, fresh clone.

**Comment by iinsertNameHere** [comment]
@JustBuddy 
I reset the repo to commit 4e37f0fcaf4a82a435ddf9ff55282a058a65464f which is just before the multi disk support was added. I will retry adding Multiple disks support. The issues should be fixed for now.

**Comment by JustBuddy** [comment]
Yep, catnip works as of now.
You might want to work on new features in a different branch, you can PR those back into main once stable.

**Comment by iinsertNameHere** [comment]
@JustBuddy  Yep, that is a good idea ;)

**Comment by iinsertNameHere** [comment]
@JustBuddy Would you be so kind to try again in [this branch](https://github.com/iinsertNameHere/catnip/tree/60) ? I remade the feature from scratch, should work better now. Documentation is in README.md

**Comment by JustBuddy** [comment]
@iinsertNameHere looking good.

![image](https://github.com/iinsertNameHere/catnip/assets/8122264/0624e55a-90f7-4c1a-bdb1-88eef49b13fd)

**Comment by JustBuddy** [comment]
@iinsertNameHere Works 👍
Will memory get a percentage like other storage?

![image](https://github.com/iinsertNameHere/catnip/assets/8122264/35231c52-1d79-48e9-b24e-d2a06b812bf2)

**Comment by iinsertNameHere** [comment]
@JustBuddy  Added percentage to memory stat.

**Comment by JustBuddy** [comment]
Thank you for the work you put into this, much appreciated!
