### ISSUE TITLE
[Feature]: Add support for showing what window manager you are using in fetch

### ISSUE THREAD

**Issue by xzi** [iinsertNameHere/catnip#61]
### Is your feature request related to a problem? Please describe:
I run i3. Presently, my fetch using catnip just shows "unknown" under the desktop manager field. This doesn't look very pretty.  

Picture of what I am talking about:
![image](https://github.com/iinsertNameHere/catnip/assets/96212687/d271ba2d-9858-4e89-8dff-d10e48e031a3)

### Describe the solution you'd like:
I think one of two solutions could work.
1. Add support for window manager detection to the desktop field and just have it that way.
2. Add a dedicated window manager section to the desktop field.

### Additional context:
First time opening a feature request issue so apologies if it isn't the correct format. Love the tool.

**Comment by iinsertNameHere** [comment]
Hey, the Desktop stat should also show If you have a Windowmanager. I will Look into it.

**Comment by xzi** [comment]
> Hey, the Desktop stat should also show If you have a Windowmanager. I will Look into it.

Ah alr. If you need any info from me lmk.

**Comment by iinsertNameHere** [comment]
My guess is that this is not a problem with catnip but with you XDG env vars. Could you check if XDG_CURRENT_DESKTOP is set?

**Comment by xzi** [comment]
> My guess is that this is not a problem with catnip but with your XDG env vars. Could you check if XDG_CURRENT_DESKTOP is set?

Apparently it is a problem with i3 debug logs not setting XDG stuff correctly. i3 debug logs only sets $DESKTOP_SESSION. I'll prob patch up catnip to work with $DESKTOP_SESSION as a fallback of a fallback later today.

**Comment by iinsertNameHere** [comment]
Okay, sounds good!
