### ISSUE TITLE
[Change]: Add more and better comments

### ISSUE THREAD

**Issue by iinsertNameHere** [iinsertNameHere/catnip#65]
### Is your change request related to a problem? Please describe:
When revisiting the Projekt after some time, IT often Takes some time to dig throu the Code and figure Out what it Dose.

### Describe what you want to change:
Adding more and better comments might Help.

**Comment by yu-kiat** [comment]
In addition a `CONTRIBUTING.md` could be added to help new contributors know what the different files do.
