### ISSUE TITLE
[Bug]: Can't use custom location for distros.toml?

### ISSUE THREAD

**Issue by yu-kiat** [iinsertNameHere/catnip#66]
### Describe the bug:
When using `catnip -c`, you can only include a custom path to the `config.toml`, so distros.toml cannot be moved to another location other than ~/.config/catnip/

### Screenshots:
![20240505_11h15m17s_grim](https://github.com/iinsertNameHere/catnip/assets/141553384/7c64788b-ee93-4d3b-97d5-5b6c1bec11a0)

### Device:
 - OS: Arch Linux
 - DE/WM: dwl
 - TERMINAL: foot

**Comment by iinsertNameHere** [comment]
Maby it would be a good idea to add a different Option for that, as you may not always want to move this File when moving the config.

Option could be: --art / -a
