### ISSUE TITLE
[Feature]: Weather stat

### ISSUE THREAD

**Issue by iinsertNameHere** [iinsertNameHere/catnip#67]
### Describe the solution you'd like:
A stat that Displays the Werther based on your IP geolocation, would be a fun Feature to have..

**Comment by yu-kiat** [comment]
weather information can be obtained by curl-ing wttr.in
```console
curl "wttr.in/NewYork?format=3"
NewYork: ☁️   +11°C
```

however, doing this takes <5 seconds, which could slow the program down considerably

**Comment by yu-kiat** [comment]
doing `curl "wttr.in/?format=3" gets the weather based of your ip address`
