### ISSUE TITLE
[Bug]: catnip -g is broken

### ISSUE THREAD

**Issue by yu-kiat** [iinsertNameHere/catnip#68]
### Describe the bug:
With the default catnip configuration file installed in ~/.config/catnip, the program errors out when doing `catnip -g` with any stat.

### Screenshots:
![20240505_22h40m01s_grim](https://github.com/iinsertNameHere/catnip/assets/141553384/fb344db6-1ecb-4223-92b9-0b3c311f610c)

### Device:
 - OS: Arch Linux
 - DE/WM: dwl
 - TERMINAL: foot

**Comment by iinsertNameHere** [comment]
Should work now @yu-kiat
