### ISSUE TITLE
[Feature]: Add build number

### ISSUE THREAD

**Issue by iinsertNameHere** [iinsertNameHere/catnip#73]
### Is your feature request related to a problem? Please describe:
When working with two different versions of catnip while developing it is sometimes hard to tell, which version is which.
 
### Describe the solution you'd like:
The idea is to use a *Gituhb action* to automatically set a BUILD_NUMBER variable inside the `definitions.nim` file.
When running catnip with `-h` it will show the build number.

### Additional context:
I don't now how *Github actions* work...

**Comment by yu-kiat** [comment]
I feel that instead of build numbers, it should be a git commit ID? Because then it would be easier to see which commit the repo is on.

**Comment by iinsertNameHere** [comment]
@yu-kiat Ohh, of cours. That is even better!
