### ISSUE TITLE
[Change]: Edits to README?

### ISSUE THREAD

**Issue by yu-kiat** [iinsertNameHere/catnip#86]
### Is your change request related to a problem? Please describe:
No.

### Describe what you want to change:
Should [usage](https://github.com/iinsertNameHere/catnip#-usage) be deleted and https://iinsertnamehere.github.io/catnip-docs/Setup/Usage.html be expanded to show full usage?

This is because both are the exact same thing currently.

### Additional context:
No,

**Comment by iinsertNameHere** [comment]
Yes, this would probably be a good idea.
