### ISSUE TITLE
[Question]:Unable to display images in cool-retro-term terminals

### ISSUE THREAD

**Issue by Yakumo-Yukari** [iinsertNameHere/catnip#87]
### Ask your Question:
In kitty terminal, the pictures in the configuration file can be displayed normally, but in cool-retro-term, the pictures will not be displayed, and the pictures can be displayed normally by using viu to output them in the terminal, but they can not be displayed in cool-retro-term when using catnip command.

**Comment by yu-kiat** [comment]
The image is shown in cool-retro-term when using the `catnip` command for me.

**Comment by yu-kiat** [comment]
Yeah, after further testing, I'm still not able to reproduce this issue.

**Comment by iinsertNameHere** [comment]
Yeah, I too can't reproduce... Sorry

**Comment by iinsertNameHere** [comment]
Dose viu Work without catnip?

**Comment by iinsertNameHere** [comment]
As @yu-kiat and myself can't reproduce the bug, I will close this Issue for now. If you want, you can open a BUG Issue and try to fix it you self.
