### ISSUE TITLE
[Feature]: Probe GPU Info

### ISSUE THREAD

**Issue by codyhod** [iinsertNameHere/catnip#90]
### Is your feature request related to a problem? Please describe:
No, not a problem - just an enhancement.

### Describe the solution you'd like:
Add an additional stat, `gpu` to round out the basic system specs already available (cpu, memory, disk space). 

### Additional context:
I would think the 'best' solution would be to pull from a shell output of `lspci | grep VGA`, strip off the basic start & end of the result, and display. e.g.

`09:00.0 VGA compatible controller: NVIDIA Corporation GA104 [GeForce RTX 3070] (rev a1)`
becomes
`NVIDIA Corporation GA104 [GeForce RTX 3070]`

Could also apply some further cleanup to this but that might become complicated (I haven't looked at the output variances of other GPUs, can't comment).

Furthermore, on the edge case that someone has multiple dedicated GPUs (so the above shell command returns multiple lines), you could just utilize the same system you're using for disks, ala gpu_0, gpu_1, etc.

I'm not familiar with `nim`, so unsure how difficult this actually is - apologies if unrealistic!

**Comment by iinsertNameHere** [comment]
hey, this is a very good idea. I will look in to it

**Comment by iinsertNameHere** [comment]
@codyhod Thx for the idea. Works now! :)
